# Generated by Django 3.2.6 on 2021-08-29 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testings',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de alta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testings',
            name='fecha_prevision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de previsión'),
        ),
    ]
